### ISSUE TITLE
Brak przebicia licytacji

### ISSUE THREAD

**Issue by Sevdariel** [matjanos/Thousand#4]
W momencie gdy pierwszy gracz zlicytuje 110 i następnie drugi nie zlicytuje poprawnie to w momencie późniejszej próby oddania karty następuje naruszenie ochrony pamięci (core dumped) i serwer się wysypuje.

**Comment by matjanos** [comment]
Trzeba spróbować opisać scenariusz, gdzie błąd jest powtarzalny. Póki co ciężko go odtworzyć.
